# Generated by Django 3.2 on 2023-01-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('no_of_employees', models.IntegerField(null=True)),
                ('est_date', models.DateField(auto_now=True, null=True)),
                ('is_govt_registered', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
